# Generated by Django 3.1.5 on 2021-01-06 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topics',
            options={'ordering': ['date_create'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
    ]
