# Generated by Django 3.1.5 on 2021-01-07 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postsApp', '0002_auto_20210106_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='postsApp.topics'),
        ),
    ]
