# Generated by Django 3.1.5 on 2021-01-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postsApp', '0005_posts_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostsLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name='User')),
                ('post', models.IntegerField(verbose_name='Post')),
                ('like', models.BooleanField(verbose_name='Like')),
                ('date_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Like',
                'verbose_name_plural': 'PostsLikes',
                'ordering': ['-date_update'],
            },
        ),
    ]
