# Generated by Django 3.1.5 on 2021-01-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0004_auto_20210111_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(auto_now=True, verbose_name='last login'),
        ),
    ]
