# Generated by Django 3.1.5 on 2021-01-12 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0006_users_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
    ]
