# Generated by Django 3.1.5 on 2021-01-12 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0007_auto_20210112_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
