# Generated by Django 3.1.5 on 2021-03-14 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0011_chat_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='test',
            new_name='user',
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='usersApp.users'),
            preserve_default=False,
        ),
    ]
