# Generated by Django 3.1.5 on 2021-03-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersApp', '0012_auto_20210314_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
